# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:8.0.3-fpm-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "./sampleapp/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          working_directory: ./sampleapp
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "./sampleapp/composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "./sampleapp/package.json" }}
            - node-v1-
      - run:
          working_directory: ./sampleapp
          command: yarn install
      - save_cache:
          key: node-v1-{{ checksum "./sampleapp/package.json" }}
          paths:
            - node_modules

      # prepare the database
      - run:
          working_directory: ./sampleapp
          command: touch storage/database.sqlite
      - run:
          working_directory: ./sampleapp
          command: php artisan migrate --env=testing --database=sqlite --force
      # run tests with phpunit or codecept
      - run:
          working_directory: ./sampleapp
          command: ./vendor/bin/phpunit
      - run:
          working_directory: ./sampleapp
          command: ./vendor/bin/codecept build
      - run:
          working_directory: ./sampleapp
          command: ./vendor/bin/codecept run
